apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: ${SVC_NAME}
  namespace: default
spec:
  minReplicas: 1
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${SVC_NAME}
  targetCPUUtilizationPercentage: 100