apiVersion: v1
kind: Service
metadata:
  name: ${SVC_NAME}
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30123
  selector:
    service: currency-exchange
    type: backend